name: Build and Upload to S3

on:
  push:
    branches:
      - main
      -
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: smallwebserverbuild

jobs:
  deploy:
    name: EC2 배포
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload JAR to S3
        run: |
          aws s3 cp build/libs/SmallWebServer-1.0-SNAPSHOT.jar s3://${{ env.S3_BUCKET_NAME }}/deploy/SmallWebServer-1.0-SNAPSHOT.jar